require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RootsController do

  def mock_root(stubs={})
    @mock_root ||= mock_model(Root, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all roots as @roots" do
      Root.stub(:all) { [mock_root] }
      get :index
      assigns(:roots).should eq([mock_root])
    end
  end

  describe "GET show" do
    it "assigns the requested root as @root" do
      Root.stub(:find).with("37") { mock_root }
      get :show, :id => "37"
      assigns(:root).should be(mock_root)
    end
  end

  describe "GET new" do
    it "assigns a new root as @root" do
      Root.stub(:new) { mock_root }
      get :new
      assigns(:root).should be(mock_root)
    end
  end

  describe "GET edit" do
    it "assigns the requested root as @root" do
      Root.stub(:find).with("37") { mock_root }
      get :edit, :id => "37"
      assigns(:root).should be(mock_root)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created root as @root" do
        Root.stub(:new).with({'these' => 'params'}) { mock_root(:save => true) }
        post :create, :root => {'these' => 'params'}
        assigns(:root).should be(mock_root)
      end

      it "redirects to the created root" do
        Root.stub(:new) { mock_root(:save => true) }
        post :create, :root => {}
        response.should redirect_to(root_url(mock_root))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved root as @root" do
        Root.stub(:new).with({'these' => 'params'}) { mock_root(:save => false) }
        post :create, :root => {'these' => 'params'}
        assigns(:root).should be(mock_root)
      end

      it "re-renders the 'new' template" do
        Root.stub(:new) { mock_root(:save => false) }
        post :create, :root => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested root" do
        Root.stub(:find).with("37") { mock_root }
        mock_root.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :root => {'these' => 'params'}
      end

      it "assigns the requested root as @root" do
        Root.stub(:find) { mock_root(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:root).should be(mock_root)
      end

      it "redirects to the root" do
        Root.stub(:find) { mock_root(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(root_url(mock_root))
      end
    end

    describe "with invalid params" do
      it "assigns the root as @root" do
        Root.stub(:find) { mock_root(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:root).should be(mock_root)
      end

      it "re-renders the 'edit' template" do
        Root.stub(:find) { mock_root(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested root" do
      Root.stub(:find).with("37") { mock_root }
      mock_root.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the roots list" do
      Root.stub(:find) { mock_root }
      delete :destroy, :id => "1"
      response.should redirect_to(roots_url)
    end
  end

end
